DELETE http://localhost:3003/api/blogs/65c5fb404082599cc941d857
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnYWFqYSIsImlkIjoiNjVjNWZiM2E0MDgyNTk5Y2M5NDFkODUyIiwiaWF0IjoxNzA3NDc3NjE1fQ.PvN2pG3FcZz0IRrTH7NVavy6xywN5AB6JYrDrXxiWBY